config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#home'

  get 'home' => 'home#home'

  resources :algorithms, only: [:show]
  resources :about_us, only: [:index]
  
end

app/models/algorithm.rb
class Algorithm < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
end

app/controllers/algorithms_controller.rb
class AlgorithmsController < ApplicationController
  before_action :set_algorithm

  def show
  end

  private

  def set_algorithm
    @algorithm = Algorithm.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home
        @algorithms = Algorithm.all
    end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
  def index
  end
end

app/helpers/algorithms_helper.rb
module AlgorithmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_algorithms
    Algorithm.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about_us/index.html.erb
<% content_for :title do %>
    Algos | Acerca de Nosotros
<% end %>

<div class="container-fluid">
<h1>About us</h1>
</div>

app/views/algorithms/_6.html.erb
<div class="container-fluid">
  <h1><%= name %></h1>
</div>

<div class="row">
  <div class="col-md-3">
    <!-- Tabs nav -->
    <div class="nav flex-column nav-pills nav-pills-custom" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <a title="Descripción" class="nav-link mb-3 p-3 shadow active" id="descripcion" data-toggle="pill" href="#v-pills-descripcion" role="tab" aria-controls="v-pills-home" aria-selected="true">
        <i class="fa fa-align-justify"></i>
        <span class="font-weight-bold small text-uppercase">Descripción</span></a>

      <a title="¿Como funciona?" class="nav-link mb-3 p-3 shadow" id="funcionamiento" data-toggle="pill" href="#v-pills-funcionamiento" role="tab" aria-controls="v-pills-messages" aria-selected="false">
        <i class="fa fa-power-off"></i>
        <span class="font-weight-bold small text-uppercase">Funcionamiento</span></a>

      <a title="Pseudo-Código" class="nav-link mb-3 p-3 shadow" id="p-codigo" data-toggle="pill" href="#v-pills-p-codigo" role="tab" aria-controls="v-pills-settings" aria-selected="false">
        <i class="fa fa-list-alt"></i>
        <span class="font-weight-bold small text-uppercase">Pseudo-Código</span></a>

      <a title="Códigos en los principales lenguajes" class="nav-link mb-3 p-3 shadow" id="codigo" data-toggle="pill" href="#v-pills-codigo" role="tab" aria-controls="v-pills-codigo" aria-selected="false">
        <i class="fa fa-code"></i>
        <span class="font-weight-bold small text-uppercase">Código</span></a>

      <a title="Animación" class="nav-link mb-3 p-3 shadow" id="animacion" data-toggle="pill" href="#v-pills-animacion" role="tab" aria-controls="v-pills-animacion" aria-selected="false">
        <i class="fa fa-play-circle"></i>
        <span class="font-weight-bold small text-uppercase">Animación</span></a>

      <a title="Visualizar videos" class="nav-link mb-3 p-3 shadow" id="video" data-toggle="pill" href="#v-pills-video" role="tab" aria-controls="v-pills-video" aria-selected="false">
        <i class="fa fa-play"></i>
        <span class="font-weight-bold small text-uppercase">Videos</span></a>

      <a title="Bibliografía utilizada" class="nav-link mb-3 p-3 shadow" id="biblio" data-toggle="pill" href="#v-pills-biblio" role="tab" aria-controls="v-pills-biblio" aria-selected="false">
        <i class="fa fa-book"></i>
        <span class="font-weight-bold small text-uppercase">Bibliografía</span></a>
    </div>
  </div>

  <div class="col-md-9">
    <!-- Tabs content -->
    <div class="tab-content" id="v-pills-tabContent">
      <div class="tab-pane fade shadow rounded bg-white show active p-5" id="v-pills-descripcion" role="tabpanel" aria-labelledby="descripcion">
        <h4 class="font-italic mb-4">Descripción</h4>
        <div id="texto-descripcion">
          Éste es el método más simple de ordenación externa, consiste en repetir el esquema de separación en secuencias ordenadas de registros y su mezcla, para originar secuencias ordenadas de doble longitud. Se opera con el archivo original y dos archivos auxiliares.
          La idea del ordenamiento de la mezcla directa es la siguiente:
          <ol>
            <li>Inicio.</li>
            <li>Dividir la secuencia A en dos mitades denominadas B y C.</li>
            <li>Mezclar B y C combinando cada elemento en pares ordenados.</li>
            <li>Llamar A a la secuencia mezclada y repetir los pasos 1 y 2, esta vez combinando los pares en cuádruples ordenados.</li>
            <li>Repetir los pasos anteriores duplicando cada vez la longitud de las secuencias combinadas hasta que quede ordenada la secuencia original.</li>
            <li>Fin del algoritmo.</li>
          </ol>
        </div>
      </div>

      <div class="tab-pane fade shadow rounded bg-white p-5" id="v-pills-funcionamiento" role="tabpanel" aria-labelledby="funcionamiento">
        <h4 class="font-italic mb-4">Funcionamiento</h4>
        <main>
          <ol class="gradient-list">
            <li>
              El procedimiento consiste en una partición sucesiva del archivo y una fusión que produce secuencias ordenadas.
              La primera partición se hace para secuencias de longitud 1 utilizando dos archivos auxiliares y la fusión producirá
              secuencias ordenadas de longitud 2. A cada nueva partición y fusión se duplicará la longitud de las secuencias ordenadas.
              El método terminará cuando la longitud de la secuencia ordenada exceda la longitud del archivo a ordenar.
              <!--<img src="<%#= asset_path 'quick-funcionamiento-01.png' %>" alt="" class="img" id="img-algo-f">-->
            </li>
            <li>
              Consideremos el archivo: <br>
              <b>F: 19, 27, 2, 8, 36, 5, 20, 15, 6</b>
            </li>
            <li>
              El archivo F se divide en dos nuevos archivos F1 y F2: <br>
              <b>F1: 19, 2, 36, 20, 6</b> <br>
              <b>F2: 27, 8, 5, 15</b>
            </li>
            <li>
              Ahora se funden los archivos F1 y F2, formando pares ordenados: <br>
              <b>F: 19,27, 2, 8, 5, 36, 15, 20, 6</b>
            </li>
            <li>
              Se vuelve a dividir de nuevo en partes iguales y en secuencias de longitud 2 <br>
              <b>F1: 19, 27, 5, 36, 6</b>
              <b>F2: 2, 8, 15, 20</b>
            </li>
            <li>
              La fusión de los archivos producirá <br>
              <b>F: 2, 8, 19, 27, 5, 15, 20, 36, 6</b>
            </li>
            <li>
              La nueva partición será <br>
              <b>F1: 2, 8, 19, 27, 6</b> <br>
              <b>F2: 5, 15, 20, 36</b>
            </li>
            <li>
              La nueva fusión será <br>
              <b>F: 2, 5, 8, 15, 19, 20, 27, 36, 6</b>
            </li>
            <li>
              Cada operación que trata por completo el conjunto de datos en su totalidad se denomina una fase y el proceso de
              ordenación se denomina pasada. <br>
              <b>F1: 2, 5, 8, 15, 19, 20, 27, 36</b> <br>
              <b>F2: 6</b> <br>
              <b>F: 2, 5, 6, 8, 15, 19, 20, 27, 36</b> <br>
              Evidentemente, la clave de la clasificación es disminuir el número de pasadas e incrementar su tamaño; una
              secuencia ordenada es una que contiene sólo una pasada que, a su vez, contiene todos los elementos de la pasada.
            </li>
          </ol>
        </main>
      </div>

      <div class="tab-pane fade shadow rounded bg-white p-5" id="v-pills-p-codigo" role="tabpanel" aria-labelledby="p-codigo">
        <h4 class="font-italic mb-4">Pseudo-Código</h4>
        <!--<div id="texto-descripcion">
          Este algoritmo recibe un arreglo de n elementos llamado A, las variables low y high son los índices extremos del arreglo.
          La función Partition particiona o divide el arreglo para que la función principal la ordene de menor a mayor.
        </div>-->
        <p class="font-italic text-muted mb-2">
          <script src="https://gist.github.com/AlexCs389/b76a1d3f13bf70976b46dc6487149940.js"></script>
        </p>
      </div>

      <div class="tab-pane fade shadow rounded bg-white p-5" id="v-pills-codigo" role="tabpanel" aria-labelledby="codigo">
        <h4 class="font-italic mb-4">Código</h4>
        <p class="font-italic text-muted mb-2">
        <div class="warpper">
          <input class="radio" id="one" name="group" type="radio" checked>
          <input class="radio" id="two" name="group" type="radio">
          <input class="radio" id="three" name="group" type="radio">
          <div class="tabs">
            <label class="tab" id="one-tab" for="one">Java</label>
            <label class="tab" id="two-tab" for="two">Python</label>
            <label class="tab" id="three-tab" for="three">C</label>
          </div>
          <div class="panels">
            <div class="panel" id="one-panel">
              <div class="panel-title">Código en Java</div>
              <p>
                <script src="https://gist.github.com/AlexCs389/ea4c2b5f3982906d491921ecb5d7e801.js"></script>
              </p>
            </div>
            <div class="panel" id="two-panel">
              <div class="panel-title">Código en Python</div>
              <p>
                <script src="https://gist.github.com/AlexCs389/836aba50127db9076211fb4844b12f91.js"></script>
              </p>
            </div>
            <div class="panel" id="three-panel">
              <div class="panel-title">Código en C</div>
              <p>
                <script src="https://gist.github.com/AlexCs389/9b9b7a2c4482350de35f61899ab05822.js"></script>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="tab-pane fade shadow rounded bg-white p-5" id="v-pills-animacion" role="tabpanel" aria-labelledby="animacion">
        <h4 class="font-italic mb-4">Animación</h4>
        <p class="font-italic text-muted mb-2">
        <div class="card">
          <div class="card-body">
            <section class="header">Mezcla Directa</section>
            <button type="button" class="btn btn-success" id="btnPlayDirectMix" title="Iniciar la animación"><i class="fa fa-play" id="iconoPlay"></i></button>
            <button type="button" class="btn btn-danger" id="btnStopDirectMix" title="Detener la animación"><i class="fa fa-stop" id="iconoStop"></i></button>
            <button type="button" class="btn btn-warning" id="btnReiniciarDirectMix" title="Reiniciar la animación"><i class="fa fa-reply" id="iconoReiniciar"></i></button>
            <section class="container-data">
            </section>
            <script>
                new DirectMix();
            </script>
          </div>
        </div>

        </p>
      </div>

      <div class="tab-pane fade shadow rounded bg-white p-5" id="v-pills-video" role="tabpanel" aria-labelledby="video">
        <h4 class="font-italic mb-4">Videos</h4>
        <div class="container" id="video-container">
          <button id="left-btn"><i class="arrow" title="Video anterior"></i></button>
          <iframe id="carousel" width="560" height="315" src="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <a id="id-video1" href="https://www.youtube.com/embed/S7dyvQN8KK0"></a>
          <a id="id-video2" href="https://www.youtube.com/embed/7xWWV6u2TZ8"></a>
          <a id="id-video3" href="https://www.youtube.com/embed/78YazSSNDAw"></a>
          <button id="right-btn"><i class="arrow" title="Video siguiente"></i></button>
        </div>
      </div>

      <div class="tab-pane fade shadow rounded bg-white p-5" id="v-pills-biblio" role="tabpanel" aria-labelledby="biblio">
        <h4 class="font-italic mb-4">Bibliografía</h4>
        <p class="font-italic text-muted mb-2">
        <div id="texto-descripcion">

        </div>

        <div class="card shadow mb-4">
          <div class="card-body p-5">
            <ul class="list-biblio list pl-5" id="list-biblio">
              <li class="mb-3 d-flex">
                <i class="fa fa-book" aria-hidden="true"></i>
                Joyanes Aguilar, L. (2008). Fundamentos de programación: Algoritmos, estructura de datos y objetos (4a. ed. --.). Madrid: McGraw-Hill
              </li>
              <li class="mb-3 d-flex">
                <i class="fa fa-book" aria-hidden="true"></i>
                Ignacio Zahonero , Lucas García Sánchez y Luis Joyanes Aguilar, L.(2007). Estructura de datos en C++. (1a. ed.--.). Madrid: McGraw-Hill
              </li>
              <li class="mb-3 d-flex">
                <i class="fa fa-link" aria-hidden="true"></i>
                <a title="Visitar página web" href="https://es.slideshare.net/JosAntonioSandovalAc/estructura-de-datos-unidad-4-metodos-de-ordenamiento">
                  https://es.slideshare.net/JosAntonioSandovalAc/estructura-de-datos-unidad-4-metodos-de-ordenamiento
                </a>
              </li>
              <li class="mb-3 d-flex">
                <i class="fa fa-link" aria-hidden="true"></i>
                <a title="Visitar página web" href="http://academicos.azc.uam.mx/jfg/diapositivas/almacenamiento/Unidad_6.pdf">
                  http://academicos.azc.uam.mx/jfg/diapositivas/almacenamiento/Unidad_6.pdf
                </a>
              </li>
            </ul>
          </div>
        </div>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/algorithms/show.html.erb
<% content_for :title do %>
    Algos | <%= @algorithm.name %> 
<% end %>

<div class="container-fluid">   
  <%= render "algorithms/#{@algorithm.id}", name: @algorithm.name, descripcion: "Esto es un algoritmo de ordenación"%>
</div>

app/views/home/home.html.erb
<% content_for :title do %>
  Algos | Home
<% end %>

<div class="container-fluid">
  <div class="row">
    <h1 class="text-dark">Inicio</h1>
  </div>
  <div class="row">
    <p>
      El presente sitio web tiene la finalidad de servir como apoyo en la explicación de los algoritmos de ordenamiento de la
      asignatura de estructura de datos. <br> Para cada uno de los algoritmos de ordenamiento se muestra la descripción, funcionamiento,
      seudocódigo, código fuente, animación, videos y bibliografía. <br>
      Los algoritmos presentados son los siguientes:
    </p>
    <ul>
      <li>Bubble Sort</li>
      <li>Shellsort</li>
      <li>Insertion Sort</li>
      <li>Megesort</li>
      <li>Quicksort</li>
      <li>Mezcla Directa</li>
      <li>Mezcla Equilibrada</li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= yield :title %></title>
  <%= favicon_link_tag 'icon.png' %>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= javascript_include_tag params[:controller], 'data-turbolinks-track' => true if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>
  <%= stylesheet_link_tag "application", params[:controller], :media => "all", 'data-turbolinks-track' => true if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>
  <% if content_for?(:head) %>
    <%= yield(:head) %>
  <% end %>

  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  
</head>

<body>
<div class="headerMenu">
  <div class="slide-down-logo-menu">
    <a href="<%= root_path %>" title="Inicio">
      <img src="<%= asset_path 'logo.png' %>" width="45" alt="" class="header-logo">
      <img src="<%= asset_path 'logo.png' %>" width="45" alt="" class="header-logo-mobile">
    </a>
  </div>

  <div class="hamburger-menu" title="Expandir/Contraer">
    <div class="hamburger">
      <div class="one"></div>
      <div class="two"></div>
      <div class="three"></div>
    </div>
    <p>Menú</p>
  </div>
</div>

<div class="slide-down-menu">
  <div class="container-fluid h-100">
    <div class="row h-100">
      <div class="col-4 col-lg-4 h-100 p-0">
        <a href="<%= root_url %>" class="w-100 h-100 d-flex align-items-center justify-content-center section" title="Página de inicio">
          <h2 class="text-center"><i class="fa fa-home" aria-hidden="true"></i>Home</h2>
        </a>
      </div>
      <div class="col-4 col-lg-4 h-100 p-0 custom-dropdown">
        <a href="javascript:void(0)" class="w-100 h-100 d-flex align-items-center justify-content-center section">
          <h2 class="text-center"><i class="fa fa-list-ol" aria-hidden="true"></i>Algoritmos</h2>
        </a>
        <div class="custom-dropdown-content">
          <% get_algorithms.each do |algorithm| %>
            <a href="<%= algorithm_path(algorithm.id) %>"><%= algorithm.name %></a>
          <% end %>
        </div>
      </div>
      <div class="col-4 col-lg-4 h-100 p-0">
        <a href="<%= about_us_path %>" class="w-100 h-100 d-flex align-items-center justify-content-center section" title="Acerca de, Ayuda, Contacto">
          <h2 class="text-center"><i class="fa fa-info-circle" aria-hidden="true"></i>Sobre nosotros</h2>
        </a>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid mt-4">
  <%= yield %>
</div>

<!--Footer-->
<div class="footer" title="Footer">
  <div id="button"></div>
    <div id="container">
      <div id="cont">
        <div class="footer_center">
	        <h3>Unidad Multidisciplinaria Tizimín 2021 ©</h3>
        </div>
      </div>
    </div>
</div>
</body>
</html>